/* ============================================================
   DISCO'S NOT DEAD — fx.js
   Synthesized sounds, AI voices, and glitch effects.
   No audio files: everything is generated by WebAudio + speech.
   ============================================================ */

const FX = {
  soundOn: true,
  voiceOn: true,
  ctx: null,
  reduced: window.matchMedia('(prefers-reduced-motion: reduce)').matches,

  /* Call on first user gesture (browsers require it). */
  init() {
    if (!this.ctx) {
      try { this.ctx = new (window.AudioContext || window.webkitAudioContext)(); }
      catch (e) { this.ctx = null; }
    }
    if (this.ctx && this.ctx.state === 'suspended') this.ctx.resume();
    // warm the speech engine voice list
    if ('speechSynthesis' in window) speechSynthesis.getVoices();
  },

  /* ---------- tone helpers ---------- */
  tone({ freq = 440, end = null, dur = 0.15, type = 'square', vol = 0.08, when = 0 }) {
    if (!this.soundOn || !this.ctx) return;
    const t = this.ctx.currentTime + when;
    const o = this.ctx.createOscillator();
    const g = this.ctx.createGain();
    o.type = type;
    o.frequency.setValueAtTime(freq, t);
    if (end) o.frequency.exponentialRampToValueAtTime(Math.max(end, 1), t + dur);
    g.gain.setValueAtTime(vol, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    o.connect(g).connect(this.ctx.destination);
    o.start(t); o.stop(t + dur + 0.02);
  },
  noise(dur = 0.15, vol = 0.06, when = 0) {
    if (!this.soundOn || !this.ctx) return;
    const t = this.ctx.currentTime + when;
    const len = Math.max(1, Math.floor(this.ctx.sampleRate * dur));
    const buf = this.ctx.createBuffer(1, len, this.ctx.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < len; i++) d[i] = Math.random() * 2 - 1;
    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    const g = this.ctx.createGain();
    g.gain.setValueAtTime(vol, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    src.connect(g).connect(this.ctx.destination);
    src.start(t);
  },

  /* ---------- named effects ---------- */
  knock()  { this.tone({ freq: 150, end: 60, dur: 0.09, type: 'sine', vol: 0.15 }); },
  bleep()  { this.tone({ freq: 880, dur: 0.06 }); this.tone({ freq: 1320, dur: 0.08, when: 0.07 }); },
  popupSound() {
    this.tone({ freq: 660, dur: 0.05 }); this.tone({ freq: 990, dur: 0.05, when: 0.06 });
    this.tone({ freq: 1480, dur: 0.09, when: 0.12 });
  },
  chime() { // unlock — rising disco triad
    [523, 659, 784, 1047].forEach((f, i) =>
      this.tone({ freq: f, dur: 0.22, type: 'triangle', vol: 0.1, when: i * 0.09 }));
  },
  buzz()  { this.tone({ freq: 110, dur: 0.22, type: 'sawtooth', vol: 0.07 }); },
  glitchSound() {
    this.noise(0.12, 0.05);
    this.tone({ freq: 1800, end: 90, dur: 0.14, type: 'sawtooth', vol: 0.04 });
    this.tone({ freq: 220, end: 1400, dur: 0.1, type: 'square', vol: 0.03, when: 0.08 });
  },
  vacuum() { // Larry
    this.tone({ freq: 55, end: 340, dur: 0.9, type: 'sawtooth', vol: 0.1 });
    this.tone({ freq: 340, end: 50, dur: 0.8, type: 'sawtooth', vol: 0.1, when: 0.9 });
    this.noise(1.6, 0.03);
  },
  warp() { // time warp
    this.tone({ freq: 200, end: 2400, dur: 0.5, type: 'sine', vol: 0.08 });
    this.tone({ freq: 2400, end: 200, dur: 0.5, type: 'sine', vol: 0.08, when: 0.5 });
  },
  typeTick() { this.tone({ freq: 2100, dur: 0.015, vol: 0.02 }); },
  discoRiff() { // fake midi player — an original 8-note groove
    const riff = [196, 196, 247, 262, 294, 262, 247, 196];
    riff.forEach((f, i) => this.tone({ freq: f, dur: 0.14, type: 'square', vol: 0.07, when: i * 0.16 }));
    riff.forEach((f, i) => this.tone({ freq: f * 2, dur: 0.1, type: 'triangle', vol: 0.03, when: i * 0.16 }));
  },

  /* ---------- AI voices ---------- */
  pickVoice(preferFemale) {
    if (!('speechSynthesis' in window)) return null;
    const vs = speechSynthesis.getVoices().filter(v => v.lang.startsWith('en'));
    if (!vs.length) return null;
    if (preferFemale) {
      const f = vs.find(v => /samantha|victoria|karen|zira|female|ava|allison/i.test(v.name));
      if (f) return f;
    } else {
      const m = vs.find(v => /daniel|alex|fred|david|male|aaron/i.test(v.name));
      if (m) return m;
    }
    return vs[0];
  },
  speak(text, who) {
    if (!this.voiceOn || !('speechSynthesis' in window)) return;
    const clean = text.replace(/[\u{1F300}-\u{1FAFF}☀-➿]/gu, '')
                      .replace(/\s+/g, ' ').trim().slice(0, 220);
    if (!clean) return;
    const u = new SpeechSynthesisUtterance(clean);
    if (who === 'bc') { u.pitch = 0.35; u.rate = 0.85; u.voice = this.pickVoice(false); }
    else              { u.pitch = 1.8;  u.rate = 1.15; u.voice = this.pickVoice(true); }
    u.volume = 0.9;
    speechSynthesis.speak(u);
  },
  hush() { if ('speechSynthesis' in window) speechSynthesis.cancel(); },

  /* ---------- visual glitch bursts ---------- */
  screenGlitch(big = false) {
    if (this.reduced) return;
    document.body.classList.add(big ? 'glitching-hard' : 'glitching');
    this.glitchSound();
    setTimeout(() => document.body.classList.remove('glitching', 'glitching-hard'),
      big ? 700 : 350);
  },
};
